virtuoso:
  restart: always
  image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
  environment:
    DBA_PASSWORD: dba
    SPARQL_UPDATE: "true"
  volumes:
    - ./data/virtuoso:/data
    - ./scripts:/scripts
    - /usr/local/virtuoso-opensource/lib

phpserver:
  restart: always
  image: aksw/php-5.6-fpm-odbc-virtuoso
  volumes_from:
    - ontowiki
    - virtuoso
  links:
    - virtuoso

nginx:
  restart: always
  image: aksw/nginx-ontowiki
  volumes_from:
    - ontowiki
  links:
    - phpserver
  ports:
    - 8580:80

ontowiki:
  restart: always
  image: aksw/ontowiki
  links:
    - virtuoso
